CREATE SCHEMA IF NOT EXISTS samplesjpaid;

CREATE TABLE ITEM
(
    ID          BIGSERIAL PRIMARY KEY,
    NAME TEXT NOT NULL,
    DESCRIPTION TEXT,
    LAST_UPDATED TIMESTAMP NOT NULL DEFAULT NOW() --useful to identify items inserted in single transaction
);
ALTER SEQUENCE ITEM_ID_SEQ INCREMENT BY 100;
CREATE INDEX ITEM_NAME_IDX ON ITEM (NAME);