CREATE SCHEMA IF NOT EXISTS samplesjpaid;

CREATE TABLE ITEM
(
    ID          BIGSERIAL PRIMARY KEY,
    NAME TEXT NOT NULL,
    DESCRIPTION TEXT
);

CREATE TABLE ITEM_UUID_AUTO
(
    ID          UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    DESCRIPTION TEXT NOT NULL
);

CREATE TABLE ITEM_UUID
(
    ID          UUID PRIMARY KEY,
    DESCRIPTION TEXT NOT NULL
);

CREATE TABLE ITEM_NUMERIC_AUTO
(
    ID          BIGSERIAL PRIMARY KEY,
    DESCRIPTION TEXT NOT NULL
);

CREATE TABLE ITEM_NUMERIC
(
    ID          BIGSERIAL PRIMARY KEY,
    DESCRIPTION TEXT NOT NULL
);

ALTER SEQUENCE ITEM_NUMERIC_ID_SEQ INCREMENT BY 100 RESTART 100;